project_id = "qqacjsczbrzerilgapqa"

[functions.check-tier-availability]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.generate-qr-token]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-qr-token]
verify_jwt = true

[functions.verify-subscription-status]
verify_jwt = true